---
default:
  ip: "192.168.10.10"
  hostname: boxdb
  memory: 1536
  cpus: 1

  authorize: ~/.ssh/boxdb

  folders:
      - map: .
        to: /home/vagrant/boxdb
      - map: salt/roots # For masterless, mount your salt file root
        to: /srv/salt
